urls.py
from django.urls import path
from .import views
from workflowapp.views import get_employer_name, landing
#from workflowapp.views import req_rev

# OtheremployerCreateView, PersonCreateView

urlpatterns = [
    #path("", views.homepage, name="homepage"), 
    path("", views.login_request, name="homepage"),  
    path("register/", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),   
    path("password_reset", views.password_reset_request, name="password_reset"),
    path("land", views.landing, name="land"),  

    path("log_list/", views.state_log_list, name="log_list"),

    path("close/", views.closure_quest, name="close"),
    path("vq/", views.view_quests, name="vq"),
    path("vq/emp_det/<int:id>/", views.employer_detail, name="emp_det"),
    path("vq/emp_det/req_rev/<int:id>", views.closure_detail, name="req_rev"),  # New URL pattern
    path("sview/", views.supervisors_view, name="sview"),
    path("sview/emp_det/<int:id>/", views.employer_detail, name="s_emp_det"),
    path("sview/emp_det/req_rev/<int:id>", views.closure_detail, name="s_req_rev"),  # New URL pattern
    path("lmview/", views.first_reviewed_entries, name="lmview"),
    path("lmview/emp_det/<int:id>/", views.employer_detail, name="l_emp_det"),
    path("lmview/emp_det/req_rev/<int:id>", views.closure_detail, name="l_req_rev"),  # New URL pattern
    path("bdu_rev/", views.bdu_review, name="bdu_rev"),
    path("bdu_rev/emp_det/<int:id>/", views.employer_detail, name="b_emp_det"),
    path("bdu_rev/emp_det/req_rev/<int:id>", views.closure_detail, name="b_req_rev"),  # New URL pattern
    path("apvd/", views.approved_entries, name="apvd"),
    path("apvd/emp_det/<int:id>/", views.employer_detail, name="apvd_emp_det"),
    path("apvd/emp_det/req_rev/<int:id>", views.closure_detail, name="apvd_req_rev"),  # New URL pattern
    #path("req_rev/<int:id>/", views.closure_detail, name="emp_rev"),
    path('get_employer_name/', get_employer_name, name='get_employer_name'),
    path("asgnedview/", views.assigned_entries, name="asgnedview"),
    path("asgnedview/emp_det/<int:id>/", views.employer_detail, name="a_emp_det"),
    path("asgnedview/emp_det/req_rev/<int:id>", views.closure_detail, name="a_req_rev"),  # New URL pattern  
    path("logz/", views.state_log_list, name="logz"), 
    path("all/", views.all_employers, name="all"),
    path("all/all_emp_det/<int:id>/", views.employer_detail_lm, name="all_emp_det"),
    #path("all/emp_det/<int:id>/", views.employer_detail, name="all_emp_det"),
    path("sumarz/", views.assign_summaries, name="sumarz"),
    path("engag/", views.engagement_record, name="engag"),
    path("engagview/", views.view_engagements, name="engagview"),
    path("engagview/emp_eng/<int:id>/", views.employer_engagements, name="emp_eng"),
    path("engagview/rev_eng/<int:id>/", views.engagement_review, name="rev_eng"),
    path("sup_review/", views.supervisor_review, name="sup_review"),
    path("sup_review/rev_eng/<int:id>/", views.engagement_review, name="sup_rev_eng"),
    path('search/', views.search_engagements, name='search_engagements'),
    path("search/emp_eng/<int:id>/", views.employer_engagements, name="search_eng"),
    path("search/eng_detail/<int:id>/", views.engagement_details, name="eng_detail"),

    path("all_eng/", views.all_engagements, name="all_eng"),
    path("all_eng/emp_eng/<int:id>/", views.employer_engagements, name="alleng_det"),
    path("all_eng/rev_eng/<int:id>/", views.engagement_review, name="all_rev_eng"),

   
    path("engagview/emp_eng/eng_rev/<int:id>/", views.engagement_review, name="eng_rev"),\
    
    path("gencase/", views.generalcase_record, name="gencase"),
    path("genview/", views.view_records, name="genview"),

    path("genview/case_details/<int:id>/", views.case_review, name="case_details"),

    path("rev_view/", views.reviewer_view, name="rev_view"),
    path("revd_cases/", views.reviewed_cases, name="revd_cases"),
    path("revd_cases/case_details/<int:id>/", views.case_review, name="rvcase_details"),

    path("rev_view/case_details/<int:id>/", views.case_review, name="sup_rev_view"),

    path('empsearch', views.employersearch, name="empsearch"),

    path('search_bdu/', views.search_employers_bdu, name='search_bdu')
    
    
    

    




]  

workflowapp/urls.py
from django.urls import path
from .import views
from workflowapp.views import get_employer_name, landing, deed_record,DeedsDetailView
#from workflowapp.views import req_rev

# OtheremployerCreateView, PersonCreateView

urlpatterns = [
    #path("", views.homepage, name="homepage"), 
    path("", views.login_request, name="homepage"),  
    path("register/", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),   
    path("password_reset", views.password_reset_request, name="password_reset"),
    path("land", views.landing, name="land"),  

    path("log_list/", views.state_log_list, name="log_list"),

    path("close/", views.closure_quest, name="close"),
    path("vq/", views.view_quests, name="vq"),
    path("vq/emp_det/<int:id>/", views.employer_detail, name="emp_det"),
    path("vq/emp_det/req_rev/<int:id>", views.closure_detail, name="req_rev"),  # New URL pattern
    path("sview/", views.supervisors_view, name="sview"),
    path("sview/emp_det/<int:id>/", views.employer_detail, name="s_emp_det"),
    path("sview/emp_det/req_rev/<int:id>", views.closure_detail, name="s_req_rev"),  # New URL pattern
    path("lmview/", views.first_reviewed_entries, name="lmview"),
    path("lmview/emp_det/<int:id>/", views.employer_detail, name="l_emp_det"),
    path("lmview/emp_det/req_rev/<int:id>", views.closure_detail, name="l_req_rev"),  # New URL pattern
    #path("req_rev/<int:id>/", views.closure_detail, name="emp_rev"),
    path('get_employer_name/', get_employer_name, name='get_employer_name'),
    path("asgnedview/", views.assigned_entries, name="asgnedview"),
    path("asgnedview/emp_det/<int:id>/", views.employer_detail, name="a_emp_det"),
    path("asgnedview/emp_det/req_rev/<int:id>", views.closure_detail, name="a_req_rev"),  # New URL pattern  
    path("logz/", views.state_log_list, name="logz"), 
    path("all/", views.all_employers, name="all"),
    path("all/all_emp_det/<int:id>/", views.employer_detail_lm, name="all_emp_det"),
    #path("all/emp_det/<int:id>/", views.employer_detail, name="all_emp_det"),
    path("sumarz/", views.assign_summaries, name="sumarz"),
    path("engag/", views.engagement_record, name="engag"),
    path('deed/', views.deed_record, name='deed'),
    path('deedsview/', views.view_deeds, name='deedsview'),
    path('deeds/<int:id>/', views.employer_deeds, name='deeddetail'),
    path("deeds/rev_deed/<int:id>/", views.deed_review, name="rev_deed"),
    path("deed_sup_review/", views.deeds_supervisor_review, name="deed_sup_review"),
    path("deed_sup_review/rev_deed/<int:id>/", views.deed_review, name="sup_rev_deed"),
    path('delete_deeds/', views.delete_deeds, name='delete_deeds'),

    

    path('get_team_leader/', views.get_team_leader, name='get_team_leader'),

    #path('viewdeed/', views.DeedsDetailView,  name='deed-detail'),

    path("engagview/", views.view_engagements, name="engagview"),
    path("engagview/emp_eng/<int:id>/", views.employer_engagements, name="emp_eng"),
    path("engagview/rev_eng/<int:id>/", views.engagement_review, name="rev_eng"),
    path("sup_review/", views.supervisor_review, name="sup_review"),
    path("sup_review/rev_eng/<int:id>/", views.engagement_review, name="sup_rev_eng"),
    path('search/', views.search_engagements, name='search_engagements'),
    path("search/emp_eng/<int:id>/", views.employer_engagements, name="search_eng"),
    path("search/eng_detail/<int:id>/", views.engagement_details, name="eng_detail"),

   
    path("engagview/emp_eng/eng_rev/<int:id>/", views.engagement_review, name="eng_rev"),\
    
    path("gencase/", views.generalcase_record, name="gencase"),
    path("genview/", views.view_records, name="genview"),

    path("genview/case_details/<int:id>/", views.case_review, name="case_details"),

    path("rev_view/", views.reviewer_view, name="rev_view"),
    path("revd_cases/", views.reviewed_cases, name="revd_cases"),
    path("revd_cases/case_details/<int:id>/", views.case_review, name="rvcase_details"),

    path("rev_view/case_details/<int:id>/", views.case_review, name="sup_rev_view"),

    path('your_url/', views.your_view, name='your_view'),

    

    #path('rate/', views.rating_view, name='rate'),

    path('submit_feedback2/', views.submit_feedback2, name='submit_feedback2'),
    path('feedback3/', views.feedback_view, name='feedback3'),

    path('ffom', views.feedback_form4, name='feedback_form4'),
    path('jfom', views.jotfeedback, name='jotfeedback'),
    path('submit/', views.submit_feedback4, name='submit_feedback4'),
    path('jsubmit/', views.submit_jotfeedback, name='submit_jotfeedback'),

    path('send-emails/', views.send_emails, name='send_emails'),
    path('outb/', views.outbound_form, name='outb'),
    path('update_outbound/<int:outbound_id>/', views.update_outbound, name='update_outbound'),

    path('cmap/', views.company_map, name='cmap'),

    path('emploc/', views.employer_location_map, name='emploc'),

    path('empsearch', views.employersearch, name="empsearch"),

    path('search_bdu/', views.search_employers_bdu, name='search_bdu'),

    path('susp_search/', views.suspense_search, name="susp_search"),
    
]

workflows/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workflowapp.urls')),
    path('', include('feedbackapp.urls')),
    path('', include('schoolapp.urls')),
    path('', include('fliteracyapp.urls')),
    #path('', include('quick_audit.urls')),
    path('', include('feedback2024.urls')),
    path('', include('suspenseapp.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    #path("password_reset/", views.password_reset_request, name="password_reset"),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Forclosure, Employer, Engagement, Generalcase
from django.forms import ClearableFileInput


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user


class ForclosureForm(forms.ModelForm):
    attachments = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Forclosure
        fields = ['id','nssf_no','reason','remark','reviewer', 'attachments']

    def clean_nssf_no(self):
        nssf_no = self.cleaned_data.get('nssf_no')
        employer = Employer.objects.filter(nssf_no=nssf_no).first()
        if not employer:
            raise forms.ValidationError('Invalid NSSF number')
        return nssf_no

    def save(self, commit=True):
        instance = super().save(commit=False)
        employer = Employer.objects.get(nssf_no=self.cleaned_data['nssf_no'])
        instance.employer_name = employer.employer_name
        if commit:
            instance.save()
        return instance


class EngagementForm(forms.ModelForm):
    action_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    attachments = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    
    class Meta:
        model = Engagement
        fields = ['nssf_no', 'employer_name', 'activity_done','monthly_contributions','members', 'comment', 'action_date', 'reviewer','engaged_person','engaged_mobile','engaged_email']

    activity_done = forms.MultipleChoiceField(choices=Engagement.ACTIVITY_CHOICES, widget=forms.SelectMultiple)
    comment = forms.CharField(widget=forms.Textarea)
    

class EngagementSearchForm(forms.Form):
    nssf_no = forms.CharField(label='NSSF No', max_length=130)


class GeneralcaseForm(forms.ModelForm):
    action_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    attachments = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    
    class Meta:
        model = Generalcase
        fields = ['subject', 'any_other_info', 'comment', 'action_date', 'reviewer']

    comment = forms.CharField(widget=forms.Textarea)

class EmployerSearchForm(forms.Form):
    employer_name = forms.CharField(label='NAME', max_length=130)

class SearchEmployerForm(forms.Form):
    q = forms.CharField(label='Search by employer name', max_length=100)

workflowapp/templates/Deeds.html
{% extends "header10.html" %}
{% load static %}
{% block content %}

<style>
    body {
  overflow-x: hidden; /* prevent horizontal scrolling */
}

    .alert-success {
    background-color: #dff0d8;
    color: #3c763d;
    border-color: #d6e9c6;
    }
    .custom-submit-btn {
        background-color: #bfcecebe; /* Replace with your desired color code */
        color: #090909; /* Replace with the desired text color for the button */
    }
</style>

<body>
    <div class="container stu mt-5" min-width: 965px;>
        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger text-center">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-success text-center">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
        {% endif %}

        <a class="btn btn-primary mb-3" href="{% url 'deedsview' %}">
            <i class="fa fa-list"></i> Deeds Added
        </a>
        <div class="row">
            <div class="col-sm-12 text-left py-8">
                <div class="alert alert-info text-center" style="font-weight: bold;">Record Employer Deed</div>
                
                <form method="POST" enctype="multipart/form-data" action="{% url 'deed' %}" novalidate>
                    {% csrf_token %}
                    
                    {{ fm.id }}

                    <div class="row">
                        <!-- Left Column -->
                        <div class="col-sm-6">
                            <div class="mb-3">
                                <label class="form-label"><strong>NSSF No</strong><strong style="color: red;">*</strong></label>
                                <input type="text" id="id_nssf_no" name="nssf_no" class="form-control" required>
                                <div class="invalid-feedback">
                                    Please provide a valid NSSF No.
                                </div>
                            </div>

                            <div class="mb-3">
                                <label class="form-label"><strong>Employer Name</strong></label>
                                <input type="text" id="employerNameInput" name="employer_name" class="form-control" required readonly>
                            </div>

                            <!-- <div class="mb-3">
                                <label class="form-label"><strong>Branch</strong></label>
                                <input type="text" name="Branch" class="form-control">
                            </div> -->
                            <div class="mb-3">
                                <label class="form-label"><strong>Branch</strong></label>
                                
                                {{ dfm.Branch }}
                            </div>
                            <div class="mb-3">
                                <label class="form-label"><strong>Deed Source</strong></label>
                                {{ dfm.Deed_source }}   

                            </div>
                            <div class="mb-3">
                                <label class="form-label"><strong>Team Leader</strong></label>
                                {{ dfm.team_leader }}  
                                </div>
                                
                                <div class="mb-3">
                                    <label class="form-label"><strong>Legacy Status</strong></label>
                                    <input type="checkbox" name="Legacy_status" class="form-check-input">
                               
                                    <label class="form-label"><strong>Signed Deed</strong></label>
                                    <input type="checkbox" name="Signed_Deed" class="form-check-input">
                                </div>    
                                
                            <div class="mb-3">
                                <label class="form-label"><strong>Attachments</strong></label>
                                <div class="attachment-fields">
                                    <input type="file" name="attachments" multiple class="form-control-file">
                                    {% for attachment in dfm.attachments.value %}
                                        <a href="{{ attachment.file.url }}" download>{{ attachment.file.name }}</a><br>
                                    {% endfor %}
                                </div>
                                <button type="button" class="btn btn-primary btn-sm mt-2" onclick="addAttachmentField()">Add Attachment</button>
                            </div>
                            <!-- <div class="mb-3">
                                <label class="form-label"><strong>Team Leader</strong></label>
                                <input type="text" name="Team_Leader" class="form-control">
                            </div> -->
                        </div>

                        <!-- Right Column -->
                        <div class="col-sm-6">
                            <div class="mb-3">
                                <label class="form-label"><strong>From Date</strong></label>
                                <input type="date" name="From_Date" class="form-control">
                            </div>

                            <div class="mb-3">
                                <label class="form-label"><strong>To Date</strong></label>
                                <input type="date" name="To_Date" class="form-control">
                            </div>

                            <div class="mb-3">
                                <label class="form-label"><strong>First Installment Date</strong></label>
                                <input type="date" name="First_Installment_Date" class="form-control">
                            </div>

                            <div class="mb-3">
                                <label class="form-label"><strong>Second Installment Date</strong></label>
                                <input type="date" name="Second_Installment_Date" class="form-control">
                            </div>

                            <button class="btn btn-lg custom-submit-btn" type="submit">Submit</button>

                            
                            
                            <div class="mb-3 form-iteration">
                            {% for deed in dfm %}
                            {% if deed.attachments %}
                            <p><strong>Attachments:</strong></p>
                            <ul>
                            {% for attachment in deed.attachments %}
                                <li><a href="{{ attachment.file.url }}" download>{{ attachment.file.name }}</a></li>
                            {% endfor %}
                            </ul>
                            {% endif %}
                            {% endfor %}
                            
                            </div>
                        </div>

                    </div>

                    
                </form>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script>

        //Function to add more attachments
        function addAttachmentField() {
            var attachmentFieldsDiv = document.querySelector('.attachment-fields');
            var newAttachmentField = document.createElement('input');
            newAttachmentField.type = 'file';
            newAttachmentField.name = 'attachments';
            newAttachmentField.className = 'form-control-file mb-2';
            newAttachmentField.multiple = true;
            attachmentFieldsDiv.appendChild(newAttachmentField);
        }
        // function addAttachmentField() {
        //     var attachmentsDiv = document.querySelector('.attachments');
        //     var newAttachmentField = document.createElement('input');
        //     newAttachmentField.type = 'file';
        //     newAttachmentField.name = 'attachments';
        //     newAttachmentField.className = 'form-control-file mb-2';
        //     newAttachmentField.accept = '.pdf,.doc,.docx,.txt';
        //     attachmentsDiv.appendChild(newAttachmentField);
        // }
        // AJAX request for fetching employer name based on NSSF No.
        document.getElementById('id_nssf_no').addEventListener('blur', function() {
            var nssfNo = this.value;
            var employerNameInput = document.getElementById('employerNameInput');
            if (nssfNo !== '') {
                var url = '/get_employer_name/?nssf_no=' + nssfNo;
                fetch(url)
                    .then(response => response.text())
                    .then(data => {
                        employerNameInput.value = data;
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
            } else {
                employerNameInput.value = '';
            }
        });

        document.addEventListener('DOMContentLoaded', function() {
    // Get the Branch dropdown and Team Leader input elements
    var branchSelect = document.getElementById('branch_id');
    var teamLeaderInput = document.getElementById('teamLeaderInput');

    // Ensure elements are present before adding the event listener
    if (branchSelect && teamLeaderInput) {
        // Add change event listener to the Branch dropdown
        branchSelect.addEventListener('change', function() {
            var selectedBranchId = branchSelect.value;

            // Check if a branch is selected
            if (selectedBranchId !== '') {
                // Construct the URL for the AJAX request
                var url = '{% url "get_team_leader" %}?branch_id=' + selectedBranchId;

                // Make the AJAX request to fetch the Team Leader
                fetch(url)
                    .then(response => response.json())  // Parse the response as JSON
                    .then(data => {
                        // Set the fetched Team Leader name to the input field
                        teamLeaderInput.value = data.team_leader_name;
                    })
                    .catch(error => {
                        console.error('Error fetching team leader:', error);
                    });
            } else {
                // Clear the Team Leader input if no branch is selected
                teamLeaderInput.value = '';
            }
        });
    } else {
        console.error('Branch select or Team Leader input not found.');
    }
});
    </script>
</body>

{% endblock %}

workflowapp/templates/member_suspense_search.html
{% extends "header13.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<style>
    /* Adjust the border width and color for the table */
    table.table {
        border: none;
    }

    /* Adjust the border width and color for the table cells */
    table.table td,
    table.table th {
        border: none;
        font-size: 10px;
    }

    /* Remove the default table cell padding */
    table.table td,
    table.table th {
        padding: 0;
        font-size: 10px;
    }

    /* Add borders to the columns under col-sm-4 and col-sm-8 */
    .bordered-col {
        border: 1px solid #ccc;
        padding: 10px;
        border-radius: 10px;
        margin-bottom: 20px;
        overflow: auto; /* Enable overflow scrolling */
        max-height: 900px; /* Set a maximum height for the container to trigger scrolling */
        max-width: 100%
    }

    /* Ensure content fits on one page */
    .container {
        overflow-x: hidden;
    }

    /* Adjust the width of the container if needed */
    .container {
        max-width: 95%; /* Change the max-width value if necessary */
    }

    /* Prevent text wrapping in table cells */
    .table-container table td,
    .table-container table th {
        white-space: nowrap;
    }

    /* Adjust button size */
    .btn {
        font-size: 10px;
        padding: 4px 8px; /* Adjust padding to fit smaller buttons */
        line-height: 1; /* Ensure button height matches font size */
    }

    /* Override Bootstrap styles for smaller screens */
    @media (max-width: 767.98px) {
        .col-sm-4,
        .col-sm-7 {
            padding: 5px;
            margin-bottom: 10px;
        }
    }
    /* Add space below the form */
    .my-form {
        margin-bottom: 30px; /* Adjust the value to control the space */
    }

</style>
{% endblock %}

{% block content %}
<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success text-center">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="row">

        <div class="col-sm-11 bordered-col mx-3">
            <div class="table-container">

                <h6>NSSF REGISTERED EMPLOYER WILD SEARCH ENGINE </h6>

                

                <form method="GET" action="" class="my-form">
                    <div class="input-group flex-nowrap">
                        <!-- Manually render the form field -->
                        <input type="text" class="form-control" id="id_q" name="q" placeholder="Enter Name To search" aria-label="Name" aria-describedby="name-addon" value="{{ search_form.q.value|default:'' }}">
                
                        <!-- Submit button -->
                        <button type="submit" class="btn btn-primary" id="name-addon">Search member</button>
                    </div>
                </form>
                

                <!-- Your Table -->
                <table id="ordertable2" class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>NSSF Number</th>
                            <th>Registration date</th>
                            <th>Type</th>
                            <th>Role ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for member in results %}
                        <tr>
                            <td>{{ member.member_name }}</td>
                            <td>{{ member.employerno }}</td>
                            <td>{{ member.employer_name }}</td>
                            <td>{{ member.end_date}}</td>
                            <td>{{ member.init_member_suspense_contr}}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5">No results found.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        // Custom sorting function for datetime column
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "datetime-pre": function(a) {
                return new Date(a).getTime();
            },
            "datetime-asc": function(a, b) {
                return a - b;
            },
            "datetime-desc": function(a, b) {
                return b - a;
            }
        });

        $('#order-table').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true, // Enable responsive mode
            "columnDefs": [
                { "type": "datetime", "targets": 2 } // Set the datetime sorting type for the 'Created at' column
            ],
            "order": [[2, 'desc']] // Specify the column index for ordering (2 for the 'Created at' column)
        });

        $('#ordertable2').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true, // Enable responsive mode
            "columnDefs": [
                { "type": "datetime", "targets": 2 } // Set the datetime sorting type for the 'Created at' column
            ],
            "order": [[2, 'desc']] // Specify the column index for ordering (2 for the 'Created at' column)
        });
    });
</script>
{% endblock %}